# Generated by Django 5.0.5 on 2024-05-09 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarqatuvchi',
            options={'verbose_name': 'Tarqatuwchi', 'verbose_name_plural': 'Tarqatuvchilar'},
        ),
    ]
